name: Accept Validator

on: fork

jobs:
  accept:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # fetch-depth is set to zero to obtain everything ... which includes history, logs., refs

    - name: Accept Coding Assignment
      run: |
        echo ${GITHUB_ACTOR}
        echo ${GITHUB_REPOSITORY}
        echo ${GITHUB_REPOSITORY_OWNER}
        echo ${GITHUB_TRIGGERING_ACTOR}
